language: go

go:
  - 1.6.3
  - 1.7.1
  - tip

install:
  - go get -t ./...
  - go get github.com/golang/lint/golint
  - go get github.com/gordonklaus/ineffassign
  - go get -u github.com/client9/misspell/cmd/misspell

script:
  - diff <(echo -n) <(gofmt -s -d .)
  - ineffassign .
  - go vet ./...
  - go test -race ./...
  - misspell .

after_script:
  - golint ./...
